//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace main {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class module : global::System.Configuration.ApplicationSettingsBase {
        
        private static module defaultInstance = ((module)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new module())));
        
        public static module Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dddd  ee阀手动阀")]
        public string LastOpenDllPath {
            get {
                return ((string)(this["LastOpenDllPath"]));
            }
            set {
                this["LastOpenDllPath"] = value;
            }
        }
    }
}
